# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .get_v_2_webhooks_response_data_item_subscriptions_item_filter_and_and_item_equals import (
    GetV2WebhooksResponseDataItemSubscriptionsItemFilterAndAndItemEquals,
)
from .get_v_2_webhooks_response_data_item_subscriptions_item_filter_and_and_item_not_equals import (
    GetV2WebhooksResponseDataItemSubscriptionsItemFilterAndAndItemNotEquals,
)


class GetV2WebhooksResponseDataItemSubscriptionsItemFilterAndAndItem_Equals(
    GetV2WebhooksResponseDataItemSubscriptionsItemFilterAndAndItemEquals
):
    operator: typing_extensions.Literal["equals"]

    class Config:
        frozen = True
        
        allow_population_by_field_name = True


class GetV2WebhooksResponseDataItemSubscriptionsItemFilterAndAndItem_NotEquals(
    GetV2WebhooksResponseDataItemSubscriptionsItemFilterAndAndItemNotEquals
):
    operator: typing_extensions.Literal["not_equals"]

    class Config:
        frozen = True
        
        allow_population_by_field_name = True


GetV2WebhooksResponseDataItemSubscriptionsItemFilterAndAndItem = typing.Union[
    GetV2WebhooksResponseDataItemSubscriptionsItemFilterAndAndItem_Equals,
    GetV2WebhooksResponseDataItemSubscriptionsItemFilterAndAndItem_NotEquals,
]
