# This file was auto-generated by Fern from our API Definition.

import typing

from .post_v_2_comments_request_data_author import PostV2CommentsRequestDataAuthor
from .post_v_2_comments_request_data_record import PostV2CommentsRequestDataRecord
from .post_v_2_comments_request_data_thread_id import PostV2CommentsRequestDataThreadId

PostV2CommentsRequestData = typing.Union[
    PostV2CommentsRequestDataThreadId, PostV2CommentsRequestDataRecord, PostV2CommentsRequestDataAuthor
]
