# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode(str, enum.Enum):
    """
    The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
    """

    AF = "AF"
    AX = "AX"
    AL = "AL"
    DZ = "DZ"
    AS = "AS"
    AD = "AD"
    AO = "AO"
    AI = "AI"
    AQ = "AQ"
    AG = "AG"
    AR = "AR"
    AM = "AM"
    AW = "AW"
    AU = "AU"
    AT = "AT"
    AZ = "AZ"
    BS = "BS"
    BH = "BH"
    BD = "BD"
    BB = "BB"
    BY = "BY"
    BE = "BE"
    BZ = "BZ"
    BJ = "BJ"
    BM = "BM"
    BT = "BT"
    BO = "BO"
    BA = "BA"
    BW = "BW"
    BV = "BV"
    BR = "BR"
    IO = "IO"
    BN = "BN"
    BG = "BG"
    BF = "BF"
    BI = "BI"
    KH = "KH"
    CM = "CM"
    CA = "CA"
    CV = "CV"
    KY = "KY"
    CF = "CF"
    TD = "TD"
    CL = "CL"
    CN = "CN"
    CX = "CX"
    CC = "CC"
    CO = "CO"
    KM = "KM"
    CG = "CG"
    CD = "CD"
    CK = "CK"
    CR = "CR"
    CI = "CI"
    HR = "HR"
    CU = "CU"
    CY = "CY"
    CZ = "CZ"
    DK = "DK"
    DJ = "DJ"
    DM = "DM"
    DO = "DO"
    EC = "EC"
    EG = "EG"
    SV = "SV"
    GQ = "GQ"
    ER = "ER"
    EE = "EE"
    ET = "ET"
    FK = "FK"
    FO = "FO"
    FJ = "FJ"
    FI = "FI"
    FR = "FR"
    GF = "GF"
    PF = "PF"
    TF = "TF"
    GA = "GA"
    GM = "GM"
    GE = "GE"
    DE = "DE"
    GH = "GH"
    GI = "GI"
    GR = "GR"
    GL = "GL"
    GD = "GD"
    GP = "GP"
    GU = "GU"
    GT = "GT"
    GG = "GG"
    GN = "GN"
    GW = "GW"
    GY = "GY"
    HT = "HT"
    HM = "HM"
    VA = "VA"
    HN = "HN"
    HK = "HK"
    HU = "HU"
    IS = "IS"
    IN = "IN"
    ID = "ID"
    IR = "IR"
    IQ = "IQ"
    IE = "IE"
    IM = "IM"
    IL = "IL"
    IT = "IT"
    JM = "JM"
    JP = "JP"
    JE = "JE"
    JO = "JO"
    KZ = "KZ"
    KE = "KE"
    KI = "KI"
    KR = "KR"
    KW = "KW"
    KG = "KG"
    LA = "LA"
    LV = "LV"
    LB = "LB"
    LS = "LS"
    LR = "LR"
    LY = "LY"
    LI = "LI"
    LT = "LT"
    LU = "LU"
    MO = "MO"
    MK = "MK"
    MG = "MG"
    MW = "MW"
    MY = "MY"
    MV = "MV"
    ML = "ML"
    MT = "MT"
    MH = "MH"
    MQ = "MQ"
    MR = "MR"
    MU = "MU"
    YT = "YT"
    MX = "MX"
    FM = "FM"
    MD = "MD"
    MC = "MC"
    MN = "MN"
    ME = "ME"
    MS = "MS"
    MA = "MA"
    MZ = "MZ"
    MM = "MM"
    NA = "NA"
    NR = "NR"
    NP = "NP"
    NL = "NL"
    AN = "AN"
    NC = "NC"
    NZ = "NZ"
    NI = "NI"
    NE = "NE"
    NG = "NG"
    NU = "NU"
    NF = "NF"
    MP = "MP"
    NO = "NO"
    OM = "OM"
    PK = "PK"
    PW = "PW"
    PS = "PS"
    PA = "PA"
    PG = "PG"
    PY = "PY"
    PE = "PE"
    PH = "PH"
    PN = "PN"
    PL = "PL"
    PT = "PT"
    PR = "PR"
    QA = "QA"
    RE = "RE"
    RO = "RO"
    RU = "RU"
    RW = "RW"
    BL = "BL"
    SH = "SH"
    KN = "KN"
    LC = "LC"
    MF = "MF"
    PM = "PM"
    VC = "VC"
    WS = "WS"
    SM = "SM"
    ST = "ST"
    SA = "SA"
    SN = "SN"
    RS = "RS"
    SC = "SC"
    SL = "SL"
    SG = "SG"
    SK = "SK"
    SI = "SI"
    SB = "SB"
    SO = "SO"
    ZA = "ZA"
    GS = "GS"
    ES = "ES"
    LK = "LK"
    SD = "SD"
    SR = "SR"
    SJ = "SJ"
    SZ = "SZ"
    SE = "SE"
    CH = "CH"
    SY = "SY"
    TW = "TW"
    TJ = "TJ"
    TZ = "TZ"
    TH = "TH"
    TL = "TL"
    TG = "TG"
    TK = "TK"
    TO = "TO"
    TT = "TT"
    TN = "TN"
    TR = "TR"
    TM = "TM"
    TC = "TC"
    TV = "TV"
    UG = "UG"
    UA = "UA"
    AE = "AE"
    GB = "GB"
    US = "US"
    UM = "UM"
    UY = "UY"
    UZ = "UZ"
    VU = "VU"
    VE = "VE"
    VN = "VN"
    VG = "VG"
    VI = "VI"
    WF = "WF"
    EH = "EH"
    YE = "YE"
    ZM = "ZM"
    ZW = "ZW"

    def visit(
        self,
        af: typing.Callable[[], T_Result],
        ax: typing.Callable[[], T_Result],
        al: typing.Callable[[], T_Result],
        dz: typing.Callable[[], T_Result],
        as_: typing.Callable[[], T_Result],
        ad: typing.Callable[[], T_Result],
        ao: typing.Callable[[], T_Result],
        ai: typing.Callable[[], T_Result],
        aq: typing.Callable[[], T_Result],
        ag: typing.Callable[[], T_Result],
        ar: typing.Callable[[], T_Result],
        am: typing.Callable[[], T_Result],
        aw: typing.Callable[[], T_Result],
        au: typing.Callable[[], T_Result],
        at: typing.Callable[[], T_Result],
        az: typing.Callable[[], T_Result],
        bs: typing.Callable[[], T_Result],
        bh: typing.Callable[[], T_Result],
        bd: typing.Callable[[], T_Result],
        bb: typing.Callable[[], T_Result],
        by: typing.Callable[[], T_Result],
        be: typing.Callable[[], T_Result],
        bz: typing.Callable[[], T_Result],
        bj: typing.Callable[[], T_Result],
        bm: typing.Callable[[], T_Result],
        bt: typing.Callable[[], T_Result],
        bo: typing.Callable[[], T_Result],
        ba: typing.Callable[[], T_Result],
        bw: typing.Callable[[], T_Result],
        bv: typing.Callable[[], T_Result],
        br: typing.Callable[[], T_Result],
        io: typing.Callable[[], T_Result],
        bn: typing.Callable[[], T_Result],
        bg: typing.Callable[[], T_Result],
        bf: typing.Callable[[], T_Result],
        bi: typing.Callable[[], T_Result],
        kh: typing.Callable[[], T_Result],
        cm: typing.Callable[[], T_Result],
        ca: typing.Callable[[], T_Result],
        cv: typing.Callable[[], T_Result],
        ky: typing.Callable[[], T_Result],
        cf: typing.Callable[[], T_Result],
        td: typing.Callable[[], T_Result],
        cl: typing.Callable[[], T_Result],
        cn: typing.Callable[[], T_Result],
        cx: typing.Callable[[], T_Result],
        cc: typing.Callable[[], T_Result],
        co: typing.Callable[[], T_Result],
        km: typing.Callable[[], T_Result],
        cg: typing.Callable[[], T_Result],
        cd: typing.Callable[[], T_Result],
        ck: typing.Callable[[], T_Result],
        cr: typing.Callable[[], T_Result],
        ci: typing.Callable[[], T_Result],
        hr: typing.Callable[[], T_Result],
        cu: typing.Callable[[], T_Result],
        cy: typing.Callable[[], T_Result],
        cz: typing.Callable[[], T_Result],
        dk: typing.Callable[[], T_Result],
        dj: typing.Callable[[], T_Result],
        dm: typing.Callable[[], T_Result],
        do: typing.Callable[[], T_Result],
        ec: typing.Callable[[], T_Result],
        eg: typing.Callable[[], T_Result],
        sv: typing.Callable[[], T_Result],
        gq: typing.Callable[[], T_Result],
        er: typing.Callable[[], T_Result],
        ee: typing.Callable[[], T_Result],
        et: typing.Callable[[], T_Result],
        fk: typing.Callable[[], T_Result],
        fo: typing.Callable[[], T_Result],
        fj: typing.Callable[[], T_Result],
        fi: typing.Callable[[], T_Result],
        fr: typing.Callable[[], T_Result],
        gf: typing.Callable[[], T_Result],
        pf: typing.Callable[[], T_Result],
        tf: typing.Callable[[], T_Result],
        ga: typing.Callable[[], T_Result],
        gm: typing.Callable[[], T_Result],
        ge: typing.Callable[[], T_Result],
        de: typing.Callable[[], T_Result],
        gh: typing.Callable[[], T_Result],
        gi: typing.Callable[[], T_Result],
        gr: typing.Callable[[], T_Result],
        gl: typing.Callable[[], T_Result],
        gd: typing.Callable[[], T_Result],
        gp: typing.Callable[[], T_Result],
        gu: typing.Callable[[], T_Result],
        gt: typing.Callable[[], T_Result],
        gg: typing.Callable[[], T_Result],
        gn: typing.Callable[[], T_Result],
        gw: typing.Callable[[], T_Result],
        gy: typing.Callable[[], T_Result],
        ht: typing.Callable[[], T_Result],
        hm: typing.Callable[[], T_Result],
        va: typing.Callable[[], T_Result],
        hn: typing.Callable[[], T_Result],
        hk: typing.Callable[[], T_Result],
        hu: typing.Callable[[], T_Result],
        is_: typing.Callable[[], T_Result],
        in_: typing.Callable[[], T_Result],
        id: typing.Callable[[], T_Result],
        ir: typing.Callable[[], T_Result],
        iq: typing.Callable[[], T_Result],
        ie: typing.Callable[[], T_Result],
        im: typing.Callable[[], T_Result],
        il: typing.Callable[[], T_Result],
        it: typing.Callable[[], T_Result],
        jm: typing.Callable[[], T_Result],
        jp: typing.Callable[[], T_Result],
        je: typing.Callable[[], T_Result],
        jo: typing.Callable[[], T_Result],
        kz: typing.Callable[[], T_Result],
        ke: typing.Callable[[], T_Result],
        ki: typing.Callable[[], T_Result],
        kr: typing.Callable[[], T_Result],
        kw: typing.Callable[[], T_Result],
        kg: typing.Callable[[], T_Result],
        la: typing.Callable[[], T_Result],
        lv: typing.Callable[[], T_Result],
        lb: typing.Callable[[], T_Result],
        ls: typing.Callable[[], T_Result],
        lr: typing.Callable[[], T_Result],
        ly: typing.Callable[[], T_Result],
        li: typing.Callable[[], T_Result],
        lt: typing.Callable[[], T_Result],
        lu: typing.Callable[[], T_Result],
        mo: typing.Callable[[], T_Result],
        mk: typing.Callable[[], T_Result],
        mg: typing.Callable[[], T_Result],
        mw: typing.Callable[[], T_Result],
        my: typing.Callable[[], T_Result],
        mv: typing.Callable[[], T_Result],
        ml: typing.Callable[[], T_Result],
        mt: typing.Callable[[], T_Result],
        mh: typing.Callable[[], T_Result],
        mq: typing.Callable[[], T_Result],
        mr: typing.Callable[[], T_Result],
        mu: typing.Callable[[], T_Result],
        yt: typing.Callable[[], T_Result],
        mx: typing.Callable[[], T_Result],
        fm: typing.Callable[[], T_Result],
        md: typing.Callable[[], T_Result],
        mc: typing.Callable[[], T_Result],
        mn: typing.Callable[[], T_Result],
        me: typing.Callable[[], T_Result],
        ms: typing.Callable[[], T_Result],
        ma: typing.Callable[[], T_Result],
        mz: typing.Callable[[], T_Result],
        mm: typing.Callable[[], T_Result],
        na: typing.Callable[[], T_Result],
        nr: typing.Callable[[], T_Result],
        np: typing.Callable[[], T_Result],
        nl: typing.Callable[[], T_Result],
        an: typing.Callable[[], T_Result],
        nc: typing.Callable[[], T_Result],
        nz: typing.Callable[[], T_Result],
        ni: typing.Callable[[], T_Result],
        ne: typing.Callable[[], T_Result],
        ng: typing.Callable[[], T_Result],
        nu: typing.Callable[[], T_Result],
        nf: typing.Callable[[], T_Result],
        mp: typing.Callable[[], T_Result],
        no: typing.Callable[[], T_Result],
        om: typing.Callable[[], T_Result],
        pk: typing.Callable[[], T_Result],
        pw: typing.Callable[[], T_Result],
        ps: typing.Callable[[], T_Result],
        pa: typing.Callable[[], T_Result],
        pg: typing.Callable[[], T_Result],
        py: typing.Callable[[], T_Result],
        pe: typing.Callable[[], T_Result],
        ph: typing.Callable[[], T_Result],
        pn: typing.Callable[[], T_Result],
        pl: typing.Callable[[], T_Result],
        pt: typing.Callable[[], T_Result],
        pr: typing.Callable[[], T_Result],
        qa: typing.Callable[[], T_Result],
        re: typing.Callable[[], T_Result],
        ro: typing.Callable[[], T_Result],
        ru: typing.Callable[[], T_Result],
        rw: typing.Callable[[], T_Result],
        bl: typing.Callable[[], T_Result],
        sh: typing.Callable[[], T_Result],
        kn: typing.Callable[[], T_Result],
        lc: typing.Callable[[], T_Result],
        mf: typing.Callable[[], T_Result],
        pm: typing.Callable[[], T_Result],
        vc: typing.Callable[[], T_Result],
        ws: typing.Callable[[], T_Result],
        sm: typing.Callable[[], T_Result],
        st: typing.Callable[[], T_Result],
        sa: typing.Callable[[], T_Result],
        sn: typing.Callable[[], T_Result],
        rs: typing.Callable[[], T_Result],
        sc: typing.Callable[[], T_Result],
        sl: typing.Callable[[], T_Result],
        sg: typing.Callable[[], T_Result],
        sk: typing.Callable[[], T_Result],
        si: typing.Callable[[], T_Result],
        sb: typing.Callable[[], T_Result],
        so: typing.Callable[[], T_Result],
        za: typing.Callable[[], T_Result],
        gs: typing.Callable[[], T_Result],
        es: typing.Callable[[], T_Result],
        lk: typing.Callable[[], T_Result],
        sd: typing.Callable[[], T_Result],
        sr: typing.Callable[[], T_Result],
        sj: typing.Callable[[], T_Result],
        sz: typing.Callable[[], T_Result],
        se: typing.Callable[[], T_Result],
        ch: typing.Callable[[], T_Result],
        sy: typing.Callable[[], T_Result],
        tw: typing.Callable[[], T_Result],
        tj: typing.Callable[[], T_Result],
        tz: typing.Callable[[], T_Result],
        th: typing.Callable[[], T_Result],
        tl: typing.Callable[[], T_Result],
        tg: typing.Callable[[], T_Result],
        tk: typing.Callable[[], T_Result],
        to: typing.Callable[[], T_Result],
        tt: typing.Callable[[], T_Result],
        tn: typing.Callable[[], T_Result],
        tr: typing.Callable[[], T_Result],
        tm: typing.Callable[[], T_Result],
        tc: typing.Callable[[], T_Result],
        tv: typing.Callable[[], T_Result],
        ug: typing.Callable[[], T_Result],
        ua: typing.Callable[[], T_Result],
        ae: typing.Callable[[], T_Result],
        gb: typing.Callable[[], T_Result],
        us: typing.Callable[[], T_Result],
        um: typing.Callable[[], T_Result],
        uy: typing.Callable[[], T_Result],
        uz: typing.Callable[[], T_Result],
        vu: typing.Callable[[], T_Result],
        ve: typing.Callable[[], T_Result],
        vn: typing.Callable[[], T_Result],
        vg: typing.Callable[[], T_Result],
        vi: typing.Callable[[], T_Result],
        wf: typing.Callable[[], T_Result],
        eh: typing.Callable[[], T_Result],
        ye: typing.Callable[[], T_Result],
        zm: typing.Callable[[], T_Result],
        zw: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AF:
            return af()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AX:
            return ax()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AL:
            return al()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.DZ:
            return dz()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AS:
            return as_()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AD:
            return ad()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AO:
            return ao()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AI:
            return ai()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AQ:
            return aq()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AG:
            return ag()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AR:
            return ar()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AM:
            return am()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AW:
            return aw()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AU:
            return au()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AT:
            return at()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AZ:
            return az()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BS:
            return bs()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BH:
            return bh()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BD:
            return bd()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BB:
            return bb()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BY:
            return by()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BE:
            return be()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BZ:
            return bz()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BJ:
            return bj()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BM:
            return bm()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BT:
            return bt()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BO:
            return bo()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BA:
            return ba()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BW:
            return bw()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BV:
            return bv()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BR:
            return br()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.IO:
            return io()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BN:
            return bn()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BG:
            return bg()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BF:
            return bf()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BI:
            return bi()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.KH:
            return kh()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CM:
            return cm()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CA:
            return ca()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CV:
            return cv()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.KY:
            return ky()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CF:
            return cf()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TD:
            return td()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CL:
            return cl()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CN:
            return cn()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CX:
            return cx()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CC:
            return cc()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CO:
            return co()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.KM:
            return km()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CG:
            return cg()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CD:
            return cd()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CK:
            return ck()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CR:
            return cr()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CI:
            return ci()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.HR:
            return hr()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CU:
            return cu()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CY:
            return cy()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CZ:
            return cz()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.DK:
            return dk()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.DJ:
            return dj()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.DM:
            return dm()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.DO:
            return do()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.EC:
            return ec()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.EG:
            return eg()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SV:
            return sv()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GQ:
            return gq()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.ER:
            return er()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.EE:
            return ee()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.ET:
            return et()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.FK:
            return fk()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.FO:
            return fo()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.FJ:
            return fj()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.FI:
            return fi()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.FR:
            return fr()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GF:
            return gf()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PF:
            return pf()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TF:
            return tf()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GA:
            return ga()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GM:
            return gm()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GE:
            return ge()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.DE:
            return de()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GH:
            return gh()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GI:
            return gi()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GR:
            return gr()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GL:
            return gl()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GD:
            return gd()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GP:
            return gp()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GU:
            return gu()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GT:
            return gt()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GG:
            return gg()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GN:
            return gn()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GW:
            return gw()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GY:
            return gy()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.HT:
            return ht()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.HM:
            return hm()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.VA:
            return va()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.HN:
            return hn()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.HK:
            return hk()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.HU:
            return hu()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.IS:
            return is_()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.IN:
            return in_()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.ID:
            return id()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.IR:
            return ir()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.IQ:
            return iq()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.IE:
            return ie()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.IM:
            return im()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.IL:
            return il()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.IT:
            return it()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.JM:
            return jm()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.JP:
            return jp()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.JE:
            return je()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.JO:
            return jo()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.KZ:
            return kz()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.KE:
            return ke()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.KI:
            return ki()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.KR:
            return kr()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.KW:
            return kw()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.KG:
            return kg()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.LA:
            return la()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.LV:
            return lv()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.LB:
            return lb()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.LS:
            return ls()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.LR:
            return lr()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.LY:
            return ly()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.LI:
            return li()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.LT:
            return lt()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.LU:
            return lu()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MO:
            return mo()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MK:
            return mk()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MG:
            return mg()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MW:
            return mw()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MY:
            return my()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MV:
            return mv()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.ML:
            return ml()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MT:
            return mt()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MH:
            return mh()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MQ:
            return mq()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MR:
            return mr()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MU:
            return mu()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.YT:
            return yt()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MX:
            return mx()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.FM:
            return fm()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MD:
            return md()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MC:
            return mc()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MN:
            return mn()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.ME:
            return me()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MS:
            return ms()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MA:
            return ma()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MZ:
            return mz()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MM:
            return mm()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.NA:
            return na()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.NR:
            return nr()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.NP:
            return np()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.NL:
            return nl()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AN:
            return an()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.NC:
            return nc()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.NZ:
            return nz()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.NI:
            return ni()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.NE:
            return ne()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.NG:
            return ng()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.NU:
            return nu()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.NF:
            return nf()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MP:
            return mp()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.NO:
            return no()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.OM:
            return om()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PK:
            return pk()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PW:
            return pw()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PS:
            return ps()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PA:
            return pa()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PG:
            return pg()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PY:
            return py()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PE:
            return pe()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PH:
            return ph()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PN:
            return pn()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PL:
            return pl()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PT:
            return pt()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PR:
            return pr()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.QA:
            return qa()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.RE:
            return re()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.RO:
            return ro()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.RU:
            return ru()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.RW:
            return rw()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.BL:
            return bl()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SH:
            return sh()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.KN:
            return kn()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.LC:
            return lc()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.MF:
            return mf()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.PM:
            return pm()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.VC:
            return vc()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.WS:
            return ws()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SM:
            return sm()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.ST:
            return st()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SA:
            return sa()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SN:
            return sn()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.RS:
            return rs()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SC:
            return sc()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SL:
            return sl()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SG:
            return sg()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SK:
            return sk()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SI:
            return si()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SB:
            return sb()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SO:
            return so()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.ZA:
            return za()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GS:
            return gs()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.ES:
            return es()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.LK:
            return lk()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SD:
            return sd()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SR:
            return sr()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SJ:
            return sj()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SZ:
            return sz()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SE:
            return se()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.CH:
            return ch()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.SY:
            return sy()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TW:
            return tw()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TJ:
            return tj()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TZ:
            return tz()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TH:
            return th()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TL:
            return tl()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TG:
            return tg()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TK:
            return tk()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TO:
            return to()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TT:
            return tt()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TN:
            return tn()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TR:
            return tr()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TM:
            return tm()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TC:
            return tc()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.TV:
            return tv()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.UG:
            return ug()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.UA:
            return ua()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.AE:
            return ae()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.GB:
            return gb()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.US:
            return us()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.UM:
            return um()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.UY:
            return uy()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.UZ:
            return uz()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.VU:
            return vu()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.VE:
            return ve()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.VN:
            return vn()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.VG:
            return vg()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.VI:
            return vi()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.WF:
            return wf()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.EH:
            return eh()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.YE:
            return ye()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.ZM:
            return zm()
        if self is PutV2ObjectsObjectRecordsResponseDataValuesValueItemPhoneNumberCountryCode.ZW:
            return zw()
