# This file was auto-generated by Fern from our API Definition.

import typing

from .attribute_default_value_one import AttributeDefaultValueOne
from .attribute_default_value_zero import AttributeDefaultValueZero

AttributeDefaultValue = typing.Union[AttributeDefaultValueZero, AttributeDefaultValueOne]
