# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_actor_reference import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemActorReference,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_checkbox import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemCheckbox,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_currency import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemCurrency,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_date import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemDate,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_domain import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemDomain,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_email_address import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemEmailAddress,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_interaction import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemInteraction,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_location import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemLocation,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_number import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemNumber,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_personal_name import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemPersonalName,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_phone_number import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemPhoneNumber,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_rating import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemRating,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_record_reference import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemRecordReference,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_select import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemSelect,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_status import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemStatus,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_text import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemText,
)
from .put_v_2_lists_list_entries_entry_id_response_data_entry_values_value_item_timestamp import (
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemTimestamp,
)


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_ActorReference(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemActorReference
):
    attribute_type: typing_extensions.Literal["actor-reference"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Checkbox(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemCheckbox
):
    attribute_type: typing_extensions.Literal["checkbox"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Currency(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemCurrency
):
    attribute_type: typing_extensions.Literal["currency"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Date(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemDate
):
    attribute_type: typing_extensions.Literal["date"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Domain(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemDomain
):
    attribute_type: typing_extensions.Literal["domain"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_EmailAddress(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemEmailAddress
):
    attribute_type: typing_extensions.Literal["email-address"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_RecordReference(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemRecordReference
):
    attribute_type: typing_extensions.Literal["record-reference"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Interaction(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemInteraction
):
    attribute_type: typing_extensions.Literal["interaction"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Location(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemLocation
):
    attribute_type: typing_extensions.Literal["location"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Number(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemNumber
):
    attribute_type: typing_extensions.Literal["number"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_PersonalName(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemPersonalName
):
    attribute_type: typing_extensions.Literal["personal-name"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_PhoneNumber(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemPhoneNumber
):
    attribute_type: typing_extensions.Literal["phone-number"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Status(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemStatus
):
    attribute_type: typing_extensions.Literal["status"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Rating(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemRating
):
    attribute_type: typing_extensions.Literal["rating"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Select(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemSelect
):
    attribute_type: typing_extensions.Literal["select"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Text(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemText
):
    attribute_type: typing_extensions.Literal["text"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Timestamp(
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItemTimestamp
):
    attribute_type: typing_extensions.Literal["timestamp"]

    class Config:
        frozen = True
        
        populate_by_name = True


PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem = typing.Union[
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_ActorReference,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Checkbox,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Currency,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Date,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Domain,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_EmailAddress,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_RecordReference,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Interaction,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Location,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Number,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_PersonalName,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_PhoneNumber,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Status,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Rating,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Select,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Text,
    PutV2ListsListEntriesEntryIdResponseDataEntryValuesValueItem_Timestamp,
]
