# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class OutputValueInteractedAtInteractionType(str, enum.Enum):
    """
    The type of interaction e.g. calendar or email.
    """

    EMAIL = "email"
    CALENDAR_EVENT = "calendar-event"

    def visit(self, email: typing.Callable[[], T_Result], calendar_event: typing.Callable[[], T_Result]) -> T_Result:
        if self is OutputValueInteractedAtInteractionType.EMAIL:
            return email()
        if self is OutputValueInteractedAtInteractionType.CALENDAR_EVENT:
            return calendar_event()
