# This file was auto-generated by Fern from our API Definition.

import typing

from .post_v_2_webhooks_response_data_subscriptions_item_filter_and import (
    PostV2WebhooksResponseDataSubscriptionsItemFilterAnd,
)
from .post_v_2_webhooks_response_data_subscriptions_item_filter_or import (
    PostV2WebhooksResponseDataSubscriptionsItemFilterOr,
)

PostV2WebhooksResponseDataSubscriptionsItemFilter = typing.Union[
    PostV2WebhooksResponseDataSubscriptionsItemFilterOr, PostV2WebhooksResponseDataSubscriptionsItemFilterAnd
]
