# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_actor_reference import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemActorReference,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_checkbox import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemCheckbox,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_currency import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemCurrency,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_date import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemDate,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_domain import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemDomain,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_email_address import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemEmailAddress,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_interaction import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemInteraction,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_location import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemLocation,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_number import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemNumber,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_personal_name import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemPersonalName,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_phone_number import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemPhoneNumber,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_rating import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemRating,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_record_reference import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemRecordReference,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_select import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemSelect,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_status import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemStatus,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_text import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemText,
)
from .patch_v_2_objects_object_records_record_id_response_data_values_value_item_timestamp import (
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemTimestamp,
)


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_ActorReference(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemActorReference
):
    attribute_type: typing_extensions.Literal["actor-reference"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Checkbox(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemCheckbox
):
    attribute_type: typing_extensions.Literal["checkbox"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Currency(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemCurrency
):
    attribute_type: typing_extensions.Literal["currency"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Date(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemDate
):
    attribute_type: typing_extensions.Literal["date"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Domain(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemDomain
):
    attribute_type: typing_extensions.Literal["domain"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_EmailAddress(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemEmailAddress
):
    attribute_type: typing_extensions.Literal["email-address"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_RecordReference(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemRecordReference
):
    attribute_type: typing_extensions.Literal["record-reference"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Interaction(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemInteraction
):
    attribute_type: typing_extensions.Literal["interaction"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Location(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemLocation
):
    attribute_type: typing_extensions.Literal["location"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Number(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemNumber
):
    attribute_type: typing_extensions.Literal["number"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_PersonalName(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemPersonalName
):
    attribute_type: typing_extensions.Literal["personal-name"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_PhoneNumber(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemPhoneNumber
):
    attribute_type: typing_extensions.Literal["phone-number"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Status(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemStatus
):
    attribute_type: typing_extensions.Literal["status"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Rating(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemRating
):
    attribute_type: typing_extensions.Literal["rating"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Select(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemSelect
):
    attribute_type: typing_extensions.Literal["select"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Text(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemText
):
    attribute_type: typing_extensions.Literal["text"]

    class Config:
        frozen = True
        
        populate_by_name = True


class PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Timestamp(
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItemTimestamp
):
    attribute_type: typing_extensions.Literal["timestamp"]

    class Config:
        frozen = True
        
        populate_by_name = True


PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem = typing.Union[
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_ActorReference,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Checkbox,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Currency,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Date,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Domain,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_EmailAddress,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_RecordReference,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Interaction,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Location,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Number,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_PersonalName,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_PhoneNumber,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Status,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Rating,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Select,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Text,
    PatchV2ObjectsObjectRecordsRecordIdResponseDataValuesValueItem_Timestamp,
]
