# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions

PatchV2TargetIdentifierAttributesAttributeRequestDataDefaultValueZeroTemplate = typing.Union[
    typing_extensions.Literal["current-user"], str
]
