# This file was auto-generated by Fern from our API Definition.

import typing

from .patch_v_2_webhooks_webhook_id_request_data_subscriptions_item_filter_and import (
    PatchV2WebhooksWebhookIdRequestDataSubscriptionsItemFilterAnd,
)
from .patch_v_2_webhooks_webhook_id_request_data_subscriptions_item_filter_or import (
    PatchV2WebhooksWebhookIdRequestDataSubscriptionsItemFilterOr,
)

PatchV2WebhooksWebhookIdRequestDataSubscriptionsItemFilter = typing.Union[
    PatchV2WebhooksWebhookIdRequestDataSubscriptionsItemFilterOr,
    PatchV2WebhooksWebhookIdRequestDataSubscriptionsItemFilterAnd,
]
