# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .post_v_2_webhooks_request_data_subscriptions_item_filter_and_and_item_equals import (
    PostV2WebhooksRequestDataSubscriptionsItemFilterAndAndItemEquals,
)
from .post_v_2_webhooks_request_data_subscriptions_item_filter_and_and_item_not_equals import (
    PostV2WebhooksRequestDataSubscriptionsItemFilterAndAndItemNotEquals,
)


class PostV2WebhooksRequestDataSubscriptionsItemFilterAndAndItem_Equals(
    PostV2WebhooksRequestDataSubscriptionsItemFilterAndAndItemEquals
):
    operator: typing_extensions.Literal["equals"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class PostV2WebhooksRequestDataSubscriptionsItemFilterAndAndItem_NotEquals(
    PostV2WebhooksRequestDataSubscriptionsItemFilterAndAndItemNotEquals
):
    operator: typing_extensions.Literal["not_equals"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


PostV2WebhooksRequestDataSubscriptionsItemFilterAndAndItem = typing.Union[
    PostV2WebhooksRequestDataSubscriptionsItemFilterAndAndItem_Equals,
    PostV2WebhooksRequestDataSubscriptionsItemFilterAndAndItem_NotEquals,
]
